version: "3.8"
services:

  php-apache-server:
    build:
      context: .
      target: php_apache
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +"%Y-%m-%dT%H:%M:%SZ")}
    image: php-apache
    env_file:
      - php.env
    container_name: php-apache
    volumes:
      - ./src:/var/www/html
      - ./logs/php-apache:/var/log/apache2
    ports: 
      - 8000:80
  
  mysql:
    build:
      context: .
      target: mysql
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +"%Y-%m-%dT%H:%M:%SZ")}
    image: mysql
    env_file:
      - mysql.env
    container_name: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    restart: on-failure

  phpmyadmin:
    build:
      context: .
      target: phpmyadmin
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +"%Y-%m-%dT%H:%M:%SZ")}
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    env_file:
    - phpmyadmin.env
    volumes:
      - ./logs/phpmyadmin:/var/log/apache2